name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ab33901e-d2a9-4ca0-9211-4a227f40e74d
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}